In [ ]:
import pandas as pd
import numpy as np

In [ ]:
Nurse = ["n1","n2","n3","n4","n5","n6","n7","n8","n9","n10"]
Start = [4,7,1,10,22,22,0,15,17,12]
End = [6,10,4,20,24,23,7,19,21,15]
Salary = [10,20,50,21,20,11,10,51,21,20]
min=10000000000000000000000
max=0
for i in End:
  if i>max:
    max=i
final=["No"]*(max)
ratio=[]
for i in range(0,len(Salary)):
  duration=(End[i]-Start[i])
  ratio.append(Salary[i]/duration)


for i in range(0,len(ratio)):
  for j in range(0,len(ratio)-i-1):
    if ratio[j]>ratio[j+1]:
      ratio[j],ratio[j+1]=ratio[j+1],ratio[j]
      Nurse[j],Nurse[j+1]=Nurse[j+1],Nurse[j]
      Salary[j],Salary[j+1]=Salary[j+1],Salary[j]
      Start[j],Start[j+1]=Start[j+1],Start[j]
      End[j],End[j+1]=End[j+1],End[j]

print(ratio)
print(Start)
print(End)
print(Nurse)
k=1
sal=0
for i in range(0,len(ratio)):
  if Start[i]<=k and End[i]>=k:
    final[i]=Nurse[i]
    sal+=Salary[i]
  
c=0
for i in final:
  if i!='No':
    c=c+1
print("THE SCHEDULING OF NURSES IS",final)
print("THE NUMBER OF NURSES THAT CAN BE ASSIGNED ARE ",c," AND THE SALARY IS ",sal)

[1.4285714285714286, 2.1, 5.0, 5.25, 6.666666666666667, 6.666666666666667, 10.0, 11.0, 12.75, 16.666666666666668]
[0, 10, 4, 17, 7, 12, 22, 22, 15, 1]
[7, 20, 6, 21, 10, 15, 24, 23, 19, 4]
['n7', 'n4', 'n1', 'n9', 'n2', 'n10', 'n5', 'n6', 'n8', 'n3']
THE SCHEDULING OF NURSES IS ['n7', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'n3', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No']
THE NUMBER OF NURSES THAT CAN BE ASSIGNED ARE  2  AND THE SALARY IS  60


In [ ]:
Nurse = ["n1","n2","n3","n4","n5","n6","n7","n8","n9","n10"]
Start = [4,7,1,10,22,22,0,15,17,12]
End = [6,10,4,20,24,23,7,19,21,15]
Salary = [10,20,50,21,20,11,10,51,21,20]
min=10000000000000000000000
minsal = 0
pointer = 0

l = len(Nurse)
timing =[]
for i in range(0,24):
  timing.append(i)

matrix = np.zeros((len(timing),l)).astype(int)

for i in range(l):
  for j in range(Start[i],End[i]):
    matrix[j][i] = 1 

print(matrix)

shift = []
cp = []
for i in range(23,-1,-1):
  for j in range(l):
    if(matrix[i][j]==1):
      cp.append(j)

  for x in cp:
    if(Salary[x]<min):
      min = Salary[x]
      pointer = x

  shift.append(Nurse[pointer])
  minsal += Salary[x]

  for y in range(0,24):
    matrix[y][pointer] = 0

  cp = []
  min=10000000000000000000000

res = [*set(shift)]
print("Nurses in order: ", res)
print(minsal)

[[0 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 1 1 0]
 [0 0 0 1 0 0 0 1 1 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]
Nurses in order:  ['n3', 'n1', 'n8', 'n4', 'n2', 'n9', 'n5', 'n10', 'n6', 'n7']
678
